baseURL: "https://aenism.com/"
languageCode: "en-us"
title: "Aenism"
permalinks:
  ideas: /:title/
  work: /:title/
taxonomies:
  category: "categories"
  tag: "tags"
pygmentsUseClasses: false
PygmentsCodeFences: true
pygmentsStyle: "paraiso-dark"
